# 04 — NumPy Basics

**CH4114: Molecular Simulation — Tutorial 00, Part 4**

| | |
|---|---|
| **Course Instructor** | Dr. Susmita Roy |
| **TA / Author** | Shuvam Banerji Seal |

> Every code file is signed with `__author__` and documented with a `"""docstring"""` — you will see both below.

## What you will learn

- What a NumPy **array** is and how to create one
- The big five creators: `np.array`, `np.arange`, `np.linspace`, `np.zeros`/`np.ones`, `np.zeros_like`
- Random numbers with `np.random` (and why we set the **seed**)
- Degrees ↔ radians with `np.radians` / `np.degrees`
- Element-wise math on whole arrays — no loops!

```mermaid
flowchart LR
    A[Python list] -->|np.array| B[NumPy array]
    B --> C{What do you need?}
    C -->|evenly spaced numbers| D[np.linspace]
    C -->|random numbers| E[np.random]
    C -->|zeros like another array| F[np.zeros_like]
    C -->|degrees to radians| G[np.radians]
    D --> H[plot it with Matplotlib]
    E --> H
```

In [1]:
# Cell 1 — imports + signing your code
# Every Python file should start with a docstring and an __author__ tag.
# The docstring (triple quotes) describes WHAT the code does.

__author__ = "Shuvam Banerji Seal"   # sign your code — always!

import numpy as np   # import numpy with its standard short name

print("numpy version:", np.__version__)

numpy version: 2.5.2


## 1. Creating arrays

`np.array` turns a Python list into a fast, math-aware array.
An array knows its **shape** (how many elements per dimension) and its **dtype** (the type of the numbers).

In [2]:
# Build a 1D array from a list
a = np.array([1, 2, 3, 4, 5])
print("a =", a)
print("shape:", a.shape)     # (5,)  -> 5 elements, one dimension
print("dtype:", a.dtype)     # int64 -> integer elements

# Indexing and slicing work exactly like lists
print("first:", a[0])        # 1
print("last :", a[-1])       # 5
print("slice:", a[1:4])      # elements at positions 1, 2, 3

# A 2D array (a matrix): shape = (rows, columns)
m = np.array([[1, 2], [3, 4]])
print("2D array:\n", m)
print("2D shape:", m.shape)  # (2, 2)
print("row 0, col 1:", m[0, 1])   # 2

a = [1 2 3 4 5]
shape: (5,)
dtype: int64
first: 1
last : 5
slice: [2 3 4]
2D array:
 [[1 2]
 [3 4]]
2D shape: (2, 2)
row 0, col 1: 2


## 2. The big five array creators

```mermaid
flowchart TD
    A[np.arange 0,10,2] --> B[0 2 4 6 8]
    C[np.linspace 0,1,5] --> D[0 0.25 0.5 0.75 1]
    E[np.zeros 2,3] --> F[0 0 0 / 0 0 0]
    G[np.zeros_like x] --> H[same shape as x, all zeros]
    I[np.array list] --> J[your data]
```

> 🎯 **`np.linspace` is the most-used NumPy function in this course** — it
> generates the x-values for every plot you will make.

In [3]:
# np.arange(start, stop, step) -> evenly spaced INTEGERS
print("arange:", np.arange(0, 10, 2))      # [0 2 4 6 8]

# np.linspace(a, b, n) -> n evenly spaced values from a to b (INCLUSIVE)
x = np.linspace(0, 1, 5)
print("linspace:", x)                       # [0. 0.25 0.5 0.75 1.]

# np.zeros / np.ones -> arrays filled with 0 or 1
print("zeros(2,3):\n", np.zeros((2, 3)))

# np.zeros_like(x) -> zeros with the SAME shape as x
zero_grid = np.zeros_like(x)
print("zeros_like(x):", zero_grid)          # same length as x, all zeros

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
zeros(2,3):
 [[0. 0. 0.]
 [0. 0. 0.]]
zeros_like(x): [0. 0. 0. 0. 0.]


## 3. Random numbers: `np.random`

Simulations are full of randomness (Monte Carlo!). NumPy gives us every
distribution we need.

> 🎯 **Always set the seed first** (`np.random.seed(...)`) so your "random"
> results can be reproduced — the heart of scientific computing.

In [4]:
# ALWAYS set the seed first so results are reproducible
np.random.seed(42)

print("rand(5)      :", np.random.rand(5))            # uniform in [0, 1)
print("randint(0,10):", np.random.randint(0, 10, 5))  # random integers
print("normal(0,1)  :", np.random.normal(0, 1, 5))    # Gaussian
print("uniform(-1,1):", np.random.uniform(-1, 1, 5))  # uniform in [-1, 1)

# A 3x3 grid of random positions (like atom coordinates!)
positions = np.random.rand(3, 3)
print("random positions (3x3):\n", positions)

rand(5)      : [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
randint(0,10): [2 6 7 4 3]
normal(0,1)  : [ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]
uniform(-1,1): [-0.20027806 -0.90666867  0.94751104 -0.53445732 -0.81878713]
random positions (3x3):
 [[0.61838601 0.38246199 0.98323089]
 [0.46676289 0.85994041 0.68030754]
 [0.45049925 0.01326496 0.94220176]]


## 4. Angles: degrees ↔ radians

Simulation code works in **radians**, but humans think in **degrees**.
`np.radians` converts; `np.degrees` converts back. Trig functions
(`np.sin`, `np.cos`, ...) always expect **radians**.

In [5]:
deg = 90
rad = np.radians(deg)          # 90 degrees = pi/2 radians
print("radians(90) =", rad)    # ~1.5708
print("degrees(rad) =", np.degrees(rad))   # back to 90.0

# Trig functions expect radians — always convert first!
angles = np.linspace(0, 360, 37)          # 37 angles in degrees
cos_vals = np.cos(np.radians(angles))     # cos needs radians
print("cos at 0, 90, 180 deg:", cos_vals[0], cos_vals[9], cos_vals[18])

radians(90) = 1.5707963267948966
degrees(rad) = 90.0
cos at 0, 90, 180 deg: 1.0 6.123233995736766e-17 -1.0


## 5. Element-wise math — no loops needed!

NumPy applies math to **every element at once**. Here is the Lennard-Jones
potential — the exact pattern you will use in the simulation sessions:
generate a range of distances with `linspace`, then apply the formula to the
whole array.

In [6]:
# Lennard-Jones potential: E(r) = 4*eps*((sigma/r)**12 - (sigma/r)**6)
r = np.linspace(0.3, 1.0, 50)          # 50 distances in nm
sigma = 0.34                           # LJ sigma (nm)
epsilon = 0.997                        # LJ epsilon (kJ/mol)

sr = sigma / r                         # divide EVERY element by r
lj = 4 * epsilon * (sr**12 - sr**6)    # apply the formula to the whole array

print("LJ energy: min =", round(lj.min(), 4), " max =", round(lj.max(), 4))
print("mean:", round(lj.mean(), 4), " sum:", round(lj.sum(), 4))

LJ energy: min = -0.9932  max = 9.4571
mean: 0.083  sum: 4.1523


## ✅ Check yourself

1. What is the difference between `np.arange(0, 10, 2)` and `np.linspace(0, 10, 2)`?
2. Why do we always call `np.random.seed(...)` before using `np.random`?
3. Which function converts degrees to radians? Why do we need it for `np.sin`?
4. What does `np.zeros_like(x)` return, and why is it useful?

**Next:** `05_matplotlib_plotting.ipynb` — turn arrays into plots!